
import sys
import json
import argparse
import os.path

parser = argparse.ArgumentParser()

parser.add_argument('table_json', nargs='+')
parser.add_argument('-o', '--output', action='store', required=True)

args = parser.parse_args()

outfile = open(args.output, "w")

def p(*args, **kw):
    print(*args, **kw, file=outfile)

p('''
#pragma once

// Autogenerated.  Do not edit!
''')

for l in args.table_json:
    (_, filename) = os.path.split(l)
    (namespace, _) = os.path.splitext(filename)

    p(f'namespace {namespace} {{')
    with open(l) as infile:
        doc = json.load(infile)

        for key, value in doc.items():
            p(f'    constexpr const char* {key} = "{value}";')

    p('}')
    p('')
